local path = ConstEnum.icons .. "/iconnew/xmzc"

data:extend({

    {
        type = "sprite",
        name = "effect1_1-sprite",
        filename = path .. "/effect1_1.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "effect1_2-sprite",
        filename = path .. "/effect1_2.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect1_3-sprite",
        filename = path .. "/effect1_3.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect1_4-sprite",
        filename = path .. "/effect1_4.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect1_5-sprite",
        filename = path .. "/effect1_5.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect1_6-sprite",
        filename = path .. "/effect1_6.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect1_7-sprite",
        filename = path .. "/effect1_7.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect2_1-sprite",
        filename = path .. "/effect2_1.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "effect2_2-sprite",
        filename = path .. "/effect2_2.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect2_3-sprite",
        filename = path .. "/effect2_3.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect2_4-sprite",
        filename = path .. "/effect2_4.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect2_5-sprite",
        filename = path .. "/effect2_5.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect2_6-sprite",
        filename = path .. "/effect2_6.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect3_1-sprite",
        filename = path .. "/effect3_1.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "effect3_2-sprite",
        filename = path .. "/effect3_2.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect3_3-sprite",
        filename = path .. "/effect3_3.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect3_4-sprite",
        filename = path .. "/effect3_4.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect3_5-sprite",
        filename = path .. "/effect3_5.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "effect3_6-sprite",
        filename = path .. "/effect3_6.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "effect3_7-sprite",
        filename = path .. "/effect3_7.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "egg_color_bg_5-sprite",
        filename = path .. "/egg_color_bg_5.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "egg_color_bg_6-sprite",
        filename = path .. "/egg_color_bg_6.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "egg_color_bg_7-sprite",
        filename = path .. "/egg_color_bg_7.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "egg_color_bg_8-sprite",
        filename = path .. "/egg_color_bg_8.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "egg_color_bg_9-sprite",
        filename = path .. "/egg_color_bg_9.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "Icon_others_09-sprite",
        filename = path .. "/Icon_others_09.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "Icon_others_10-sprite",
        filename = path .. "/Icon_others_10.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "Icon_others_11-sprite",
        filename = path .. "/Icon_others_11.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "Icon_others_12-sprite",
        filename = path .. "/Icon_others_12.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "Icon_others_13-sprite",
        filename = path .. "/Icon_others_13.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "Icon_others_14-sprite",
        filename = path .. "/Icon_others_14.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_01-sprite",
        filename = path .. "/icon_other_01.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_02-sprite",
        filename = path .. "/icon_other_02.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_03-sprite",
        filename = path .. "/icon_other_03.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_04-sprite",
        filename = path .. "/icon_other_04.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_05-sprite",
        filename = path .. "/icon_other_05.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_06-sprite",
        filename = path .. "/icon_other_06.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_07-sprite",
        filename = path .. "/icon_other_07.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_08-sprite",
        filename = path .. "/icon_other_08.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_101-sprite",
        filename = path .. "/icon_other_101.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_102-sprite",
        filename = path .. "/icon_other_102.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_103-sprite",
        filename = path .. "/icon_other_103.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_104-sprite",
        filename = path .. "/icon_other_104.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_105-sprite",
        filename = path .. "/icon_other_105.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_106-sprite",
        filename = path .. "/icon_other_106.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_107-sprite",
        filename = path .. "/icon_other_107.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_108-sprite",
        filename = path .. "/icon_other_108.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_109-sprite",
        filename = path .. "/icon_other_109.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_110-sprite",
        filename = path .. "/icon_other_110.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_111-sprite",
        filename = path .. "/icon_other_111.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_112-sprite",
        filename = path .. "/icon_other_112.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_113-sprite",
        filename = path .. "/icon_other_113.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_114-sprite",
        filename = path .. "/icon_other_114.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_115-sprite",
        filename = path .. "/icon_other_115.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_116-sprite",
        filename = path .. "/icon_other_116.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_116_2-sprite",
        filename = path .. "/icon_other_116_2.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_117-sprite",
        filename = path .. "/icon_other_117.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_118-sprite",
        filename = path .. "/icon_other_118.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_119-sprite",
        filename = path .. "/icon_other_119.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_120-sprite",
        filename = path .. "/icon_other_120.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_121-sprite",
        filename = path .. "/icon_other_121.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_122-sprite",
        filename = path .. "/icon_other_122.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_125-sprite",
        filename = path .. "/icon_other_125.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_126-sprite",
        filename = path .. "/icon_other_126.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_127-sprite",
        filename = path .. "/icon_other_127.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_128-sprite",
        filename = path .. "/icon_other_128.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_131-sprite",
        filename = path .. "/icon_other_131.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_132-sprite",
        filename = path .. "/icon_other_132.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_133-sprite",
        filename = path .. "/icon_other_133.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_134-sprite",
        filename = path .. "/icon_other_134.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_135-sprite",
        filename = path .. "/icon_other_135.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_136-sprite",
        filename = path .. "/icon_other_136.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_137-sprite",
        filename = path .. "/icon_other_137.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_138-sprite",
        filename = path .. "/icon_other_138.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_139-sprite",
        filename = path .. "/icon_other_139.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_140-sprite",
        filename = path .. "/icon_other_140.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_141-sprite",
        filename = path .. "/icon_other_141.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_142-sprite",
        filename = path .. "/icon_other_142.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_143-sprite",
        filename = path .. "/icon_other_143.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_144-sprite",
        filename = path .. "/icon_other_144.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_145-sprite",
        filename = path .. "/icon_other_145.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_146-sprite",
        filename = path .. "/icon_other_146.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_147-sprite",
        filename = path .. "/icon_other_147.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_148-sprite",
        filename = path .. "/icon_other_148.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_149-sprite",
        filename = path .. "/icon_other_149.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_150-sprite",
        filename = path .. "/icon_other_150.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_151-sprite",
        filename = path .. "/icon_other_151.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_152-sprite",
        filename = path .. "/icon_other_152.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_153-sprite",
        filename = path .. "/icon_other_153.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_154-sprite",
        filename = path .. "/icon_other_154.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_155-sprite",
        filename = path .. "/icon_other_155.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_huanhua-sprite",
        filename = path .. "/icon_other_huanhua.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_huanzhuang-sprite",
        filename = path .. "/icon_other_huanzhuang.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_1-sprite",
        filename = path .. "/icon_other_new_1.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_10-sprite",
        filename = path .. "/icon_other_new_10.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_11-sprite",
        filename = path .. "/icon_other_new_11.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_12-sprite",
        filename = path .. "/icon_other_new_12.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_13-sprite",
        filename = path .. "/icon_other_new_13.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_14-sprite",
        filename = path .. "/icon_other_new_14.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_15-sprite",
        filename = path .. "/icon_other_new_15.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_16-sprite",
        filename = path .. "/icon_other_new_16.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_17-sprite",
        filename = path .. "/icon_other_new_17.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_18-sprite",
        filename = path .. "/icon_other_new_18.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_19-sprite",
        filename = path .. "/icon_other_new_19.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_2-sprite",
        filename = path .. "/icon_other_new_2.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_20-sprite",
        filename = path .. "/icon_other_new_20.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_25-sprite",
        filename = path .. "/icon_other_new_25.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_3-sprite",
        filename = path .. "/icon_other_new_3.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_4-sprite",
        filename = path .. "/icon_other_new_4.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_5-sprite",
        filename = path .. "/icon_other_new_5.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_6-sprite",
        filename = path .. "/icon_other_new_6.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_7-sprite",
        filename = path .. "/icon_other_new_7.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_new_8-sprite",
        filename = path .. "/icon_other_new_8.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "icon_other_new_9-sprite",
        filename = path .. "/icon_other_new_9.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_profess_record-sprite",
        filename = path .. "/icon_other_profess_record.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_reward-sprite",
        filename = path .. "/icon_other_reward.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "icon_other_shop-sprite",
        filename = path .. "/icon_other_shop.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "img_jingjielevel0 #214204-sprite",
        filename = path .. "/img_jingjielevel0 #214204.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel0-sprite",
        filename = path .. "/img_jingjielevel0.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel1 #214094-sprite",
        filename = path .. "/img_jingjielevel1 #214094.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel1-sprite",
        filename = path .. "/img_jingjielevel1.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel10 #214256-sprite",
        filename = path .. "/img_jingjielevel10 #214256.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel10-sprite",
        filename = path .. "/img_jingjielevel10.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel100-sprite",
        filename = path .. "/img_jingjielevel100.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel101-sprite",
        filename = path .. "/img_jingjielevel101.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel102-sprite",
        filename = path .. "/img_jingjielevel102.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel103-sprite",
        filename = path .. "/img_jingjielevel103.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel104-sprite",
        filename = path .. "/img_jingjielevel104.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel105-sprite",
        filename = path .. "/img_jingjielevel105.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel106-sprite",
        filename = path .. "/img_jingjielevel106.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel107-sprite",
        filename = path .. "/img_jingjielevel107.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel108-sprite",
        filename = path .. "/img_jingjielevel108.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel109-sprite",
        filename = path .. "/img_jingjielevel109.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel11 #214231-sprite",
        filename = path .. "/img_jingjielevel11 #214231.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel11-sprite",
        filename = path .. "/img_jingjielevel11.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel110-sprite",
        filename = path .. "/img_jingjielevel110.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel111-sprite",
        filename = path .. "/img_jingjielevel111.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel112-sprite",
        filename = path .. "/img_jingjielevel112.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel113-sprite",
        filename = path .. "/img_jingjielevel113.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel114-sprite",
        filename = path .. "/img_jingjielevel114.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel115-sprite",
        filename = path .. "/img_jingjielevel115.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel116-sprite",
        filename = path .. "/img_jingjielevel116.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel117-sprite",
        filename = path .. "/img_jingjielevel117.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel118-sprite",
        filename = path .. "/img_jingjielevel118.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel119-sprite",
        filename = path .. "/img_jingjielevel119.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel12 #214272-sprite",
        filename = path .. "/img_jingjielevel12 #214272.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel12-sprite",
        filename = path .. "/img_jingjielevel12.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel13 #214239-sprite",
        filename = path .. "/img_jingjielevel13 #214239.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel13-sprite",
        filename = path .. "/img_jingjielevel13.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel14 #214248-sprite",
        filename = path .. "/img_jingjielevel14 #214248.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel14-sprite",
        filename = path .. "/img_jingjielevel14.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel15 #214264-sprite",
        filename = path .. "/img_jingjielevel15 #214264.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel15-sprite",
        filename = path .. "/img_jingjielevel15.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel16 #214116-sprite",
        filename = path .. "/img_jingjielevel16 #214116.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel16-sprite",
        filename = path .. "/img_jingjielevel16.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel17 #214107-sprite",
        filename = path .. "/img_jingjielevel17 #214107.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel17-sprite",
        filename = path .. "/img_jingjielevel17.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel18 #214168-sprite",
        filename = path .. "/img_jingjielevel18 #214168.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel18-sprite",
        filename = path .. "/img_jingjielevel18.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel19 #214117-sprite",
        filename = path .. "/img_jingjielevel19 #214117.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel19-sprite",
        filename = path .. "/img_jingjielevel19.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel2 #214213-sprite",
        filename = path .. "/img_jingjielevel2 #214213.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel2-sprite",
        filename = path .. "/img_jingjielevel2.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel20 #214079-sprite",
        filename = path .. "/img_jingjielevel20 #214079.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel20-sprite",
        filename = path .. "/img_jingjielevel20.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel21 #214269-sprite",
        filename = path .. "/img_jingjielevel21 #214269.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel21-sprite",
        filename = path .. "/img_jingjielevel21.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel22 #214234-sprite",
        filename = path .. "/img_jingjielevel22 #214234.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel22-sprite",
        filename = path .. "/img_jingjielevel22.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel23 #214172-sprite",
        filename = path .. "/img_jingjielevel23 #214172.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel23-sprite",
        filename = path .. "/img_jingjielevel23.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel24 #214176-sprite",
        filename = path .. "/img_jingjielevel24 #214176.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel24-sprite",
        filename = path .. "/img_jingjielevel24.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel25 #214137-sprite",
        filename = path .. "/img_jingjielevel25 #214137.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel25-sprite",
        filename = path .. "/img_jingjielevel25.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel26-sprite",
        filename = path .. "/img_jingjielevel26.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel27-sprite",
        filename = path .. "/img_jingjielevel27.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel28-sprite",
        filename = path .. "/img_jingjielevel28.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel29-sprite",
        filename = path .. "/img_jingjielevel29.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel3 #214221-sprite",
        filename = path .. "/img_jingjielevel3 #214221.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel3-sprite",
        filename = path .. "/img_jingjielevel3.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel30-sprite",
        filename = path .. "/img_jingjielevel30.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel31-sprite",
        filename = path .. "/img_jingjielevel31.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel32-sprite",
        filename = path .. "/img_jingjielevel32.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel33-sprite",
        filename = path .. "/img_jingjielevel33.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel34-sprite",
        filename = path .. "/img_jingjielevel34.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel35-sprite",
        filename = path .. "/img_jingjielevel35.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel36-sprite",
        filename = path .. "/img_jingjielevel36.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel37-sprite",
        filename = path .. "/img_jingjielevel37.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel38-sprite",
        filename = path .. "/img_jingjielevel38.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel39-sprite",
        filename = path .. "/img_jingjielevel39.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel4 #214095-sprite",
        filename = path .. "/img_jingjielevel4 #214095.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel4-sprite",
        filename = path .. "/img_jingjielevel4.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel40-sprite",
        filename = path .. "/img_jingjielevel40.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel41-sprite",
        filename = path .. "/img_jingjielevel41.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel42-sprite",
        filename = path .. "/img_jingjielevel42.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel43-sprite",
        filename = path .. "/img_jingjielevel43.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel44-sprite",
        filename = path .. "/img_jingjielevel44.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel45-sprite",
        filename = path .. "/img_jingjielevel45.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel46-sprite",
        filename = path .. "/img_jingjielevel46.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel47-sprite",
        filename = path .. "/img_jingjielevel47.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel48-sprite",
        filename = path .. "/img_jingjielevel48.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel49-sprite",
        filename = path .. "/img_jingjielevel49.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel5 #214208-sprite",
        filename = path .. "/img_jingjielevel5 #214208.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel5-sprite",
        filename = path .. "/img_jingjielevel5.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel50-sprite",
        filename = path .. "/img_jingjielevel50.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel51-sprite",
        filename = path .. "/img_jingjielevel51.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel52-sprite",
        filename = path .. "/img_jingjielevel52.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel53-sprite",
        filename = path .. "/img_jingjielevel53.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel54-sprite",
        filename = path .. "/img_jingjielevel54.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel55-sprite",
        filename = path .. "/img_jingjielevel55.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel56-sprite",
        filename = path .. "/img_jingjielevel56.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel57-sprite",
        filename = path .. "/img_jingjielevel57.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel58-sprite",
        filename = path .. "/img_jingjielevel58.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel59-sprite",
        filename = path .. "/img_jingjielevel59.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel6 #214145-sprite",
        filename = path .. "/img_jingjielevel6 #214145.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel6-sprite",
        filename = path .. "/img_jingjielevel6.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel60-sprite",
        filename = path .. "/img_jingjielevel60.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel61-sprite",
        filename = path .. "/img_jingjielevel61.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel62-sprite",
        filename = path .. "/img_jingjielevel62.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel63-sprite",
        filename = path .. "/img_jingjielevel63.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel64-sprite",
        filename = path .. "/img_jingjielevel64.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel65-sprite",
        filename = path .. "/img_jingjielevel65.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel66-sprite",
        filename = path .. "/img_jingjielevel66.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel67-sprite",
        filename = path .. "/img_jingjielevel67.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel68-sprite",
        filename = path .. "/img_jingjielevel68.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel69-sprite",
        filename = path .. "/img_jingjielevel69.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel7 #214253-sprite",
        filename = path .. "/img_jingjielevel7 #214253.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel7-sprite",
        filename = path .. "/img_jingjielevel7.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel70-sprite",
        filename = path .. "/img_jingjielevel70.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel71-sprite",
        filename = path .. "/img_jingjielevel71.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel72-sprite",
        filename = path .. "/img_jingjielevel72.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel73-sprite",
        filename = path .. "/img_jingjielevel73.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel74-sprite",
        filename = path .. "/img_jingjielevel74.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel75-sprite",
        filename = path .. "/img_jingjielevel75.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel76-sprite",
        filename = path .. "/img_jingjielevel76.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel77-sprite",
        filename = path .. "/img_jingjielevel77.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel78-sprite",
        filename = path .. "/img_jingjielevel78.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel79-sprite",
        filename = path .. "/img_jingjielevel79.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel8 #214226-sprite",
        filename = path .. "/img_jingjielevel8 #214226.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel8-sprite",
        filename = path .. "/img_jingjielevel8.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel80-sprite",
        filename = path .. "/img_jingjielevel80.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel81-sprite",
        filename = path .. "/img_jingjielevel81.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel82-sprite",
        filename = path .. "/img_jingjielevel82.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel83-sprite",
        filename = path .. "/img_jingjielevel83.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel84-sprite",
        filename = path .. "/img_jingjielevel84.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel85-sprite",
        filename = path .. "/img_jingjielevel85.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel86-sprite",
        filename = path .. "/img_jingjielevel86.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel87-sprite",
        filename = path .. "/img_jingjielevel87.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel88-sprite",
        filename = path .. "/img_jingjielevel88.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel89-sprite",
        filename = path .. "/img_jingjielevel89.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel9 #214259-sprite",
        filename = path .. "/img_jingjielevel9 #214259.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel9-sprite",
        filename = path .. "/img_jingjielevel9.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "img_jingjielevel90-sprite",
        filename = path .. "/img_jingjielevel90.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel91-sprite",
        filename = path .. "/img_jingjielevel91.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel92-sprite",
        filename = path .. "/img_jingjielevel92.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel93-sprite",
        filename = path .. "/img_jingjielevel93.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel94-sprite",
        filename = path .. "/img_jingjielevel94.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel95-sprite",
        filename = path .. "/img_jingjielevel95.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel96-sprite",
        filename = path .. "/img_jingjielevel96.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel97-sprite",
        filename = path .. "/img_jingjielevel97.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel98-sprite",
        filename = path .. "/img_jingjielevel98.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "img_jingjielevel99-sprite",
        filename = path .. "/img_jingjielevel99.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "poem_1-sprite",
        filename = path .. "/poem_1.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "poem_2-sprite",
        filename = path .. "/poem_2.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "poem_3-sprite",
        filename = path .. "/poem_3.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "poem_4-sprite",
        filename = path .. "/poem_4.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "skill_word_1-sprite",
        filename = path .. "/skill_word_1.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_10-sprite",
        filename = path .. "/skill_word_10.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_10001-sprite",
        filename = path .. "/skill_word_10001.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "skill_word_10002-sprite",
        filename = path .. "/skill_word_10002.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_11-sprite",
        filename = path .. "/skill_word_11.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_12-sprite",
        filename = path .. "/skill_word_12.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_13-sprite",
        filename = path .. "/skill_word_13.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_14-sprite",
        filename = path .. "/skill_word_14.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_15-sprite",
        filename = path .. "/skill_word_15.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_16-sprite",
        filename = path .. "/skill_word_16.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_17-sprite",
        filename = path .. "/skill_word_17.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_18-sprite",
        filename = path .. "/skill_word_18.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_19-sprite",
        filename = path .. "/skill_word_19.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_2-sprite",
        filename = path .. "/skill_word_2.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_20-sprite",
        filename = path .. "/skill_word_20.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_21-sprite",
        filename = path .. "/skill_word_21.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_22-sprite",
        filename = path .. "/skill_word_22.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_23-sprite",
        filename = path .. "/skill_word_23.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_24-sprite",
        filename = path .. "/skill_word_24.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_25-sprite",
        filename = path .. "/skill_word_25.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_26-sprite",
        filename = path .. "/skill_word_26.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_27-sprite",
        filename = path .. "/skill_word_27.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_28-sprite",
        filename = path .. "/skill_word_28.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_29-sprite",
        filename = path .. "/skill_word_29.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_3-sprite",
        filename = path .. "/skill_word_3.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_30-sprite",
        filename = path .. "/skill_word_30.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_31-sprite",
        filename = path .. "/skill_word_31.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_32-sprite",
        filename = path .. "/skill_word_32.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_33-sprite",
        filename = path .. "/skill_word_33.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_34-sprite",
        filename = path .. "/skill_word_34.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_35-sprite",
        filename = path .. "/skill_word_35.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_4-sprite",
        filename = path .. "/skill_word_4.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_5-sprite",
        filename = path .. "/skill_word_5.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_6-sprite",
        filename = path .. "/skill_word_6.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_7-sprite",
        filename = path .. "/skill_word_7.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_8-sprite",
        filename = path .. "/skill_word_8.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "skill_word_9-sprite",
        filename = path .. "/skill_word_9.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "title_transfer_boy_1-sprite",
        filename = path .. "/title_transfer_boy_1.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_boy_2-sprite",
        filename = path .. "/title_transfer_boy_2.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_boy_3-sprite",
        filename = path .. "/title_transfer_boy_3.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_boy_4-sprite",
        filename = path .. "/title_transfer_boy_4.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_boy_5-sprite",
        filename = path .. "/title_transfer_boy_5.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_boy_6-sprite",
        filename = path .. "/title_transfer_boy_6.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_girl_1-sprite",
        filename = path .. "/title_transfer_girl_1.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_girl_2-sprite",
        filename = path .. "/title_transfer_girl_2.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_girl_3-sprite",
        filename = path .. "/title_transfer_girl_3.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_girl_4-sprite",
        filename = path .. "/title_transfer_girl_4.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_girl_5-sprite",
        filename = path .. "/title_transfer_girl_5.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "title_transfer_girl_6-sprite",
        filename = path .. "/title_transfer_girl_6.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text1-sprite",
        filename = path .. "/zerobuy_type_text1.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text2-sprite",
        filename = path .. "/zerobuy_type_text2.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text3-sprite",
        filename = path .. "/zerobuy_type_text3.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text4-sprite",
        filename = path .. "/zerobuy_type_text4.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text5-sprite",
        filename = path .. "/zerobuy_type_text5.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text6-sprite",
        filename = path .. "/zerobuy_type_text6.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zerobuy_type_text7-sprite",
        filename = path .. "/zerobuy_type_text7.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "zero_buy_text1-sprite",
        filename = path .. "/zero_buy_text1.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "zero_buy_text2-sprite",
        filename = path .. "/zero_buy_text2.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "zero_buy_text3-sprite",
        filename = path .. "/zero_buy_text3.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zero_buy_text4-sprite",
        filename = path .. "/zero_buy_text4.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "zero_buy_text5-sprite",
        filename = path .. "/zero_buy_text5.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "zero_buy_text6-sprite",
        filename = path .. "/zero_buy_text6.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "zero_buy_text7-sprite",
        filename = path .. "/zero_buy_text7.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "zero_buy_text8-sprite",
        filename = path .. "/zero_buy_text8.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "zero_buy_text9-sprite",
        filename = path .. "/zero_buy_text9.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "zhuan_1-sprite",
        filename = path .. "/zhuan_1.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zhuan_2-sprite",
        filename = path .. "/zhuan_2.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zhuan_3-sprite",
        filename = path .. "/zhuan_3.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zhuan_4-sprite",
        filename = path .. "/zhuan_4.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zhuan_5-sprite",
        filename = path .. "/zhuan_5.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zhuan_6-sprite",
        filename = path .. "/zhuan_6.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "zhuan_7-sprite",
        filename = path .. "/zhuan_7.png",
        size = 64,
    },
})
