data:extend({

    {
        type = "sprite",
        name = "10101-sprite",
        filename = ConstEnum.icons .. "/10101.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10102-sprite",
        filename = ConstEnum.icons .. "/10102.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10103-sprite",
        filename = ConstEnum.icons .. "/10103.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10104-sprite",
        filename = ConstEnum.icons .. "/10104.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10105-sprite",
        filename = ConstEnum.icons .. "/10105.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10106-sprite",
        filename = ConstEnum.icons .. "/10106.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10107-sprite",
        filename = ConstEnum.icons .. "/10107.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10108-sprite",
        filename = ConstEnum.icons .. "/10108.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10109-sprite",
        filename = ConstEnum.icons .. "/10109.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10110-sprite",
        filename = ConstEnum.icons .. "/10110.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "101101-sprite",
        filename = ConstEnum.icons .. "/101101.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "101102-sprite",
        filename = ConstEnum.icons .. "/101102.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "101105-sprite",
        filename = ConstEnum.icons .. "/101105.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "101108-sprite",
        filename = ConstEnum.icons .. "/101108.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10111-sprite",
        filename = ConstEnum.icons .. "/10111.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10112-sprite",
        filename = ConstEnum.icons .. "/10112.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10113-sprite",
        filename = ConstEnum.icons .. "/10113.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10114-sprite",
        filename = ConstEnum.icons .. "/10114.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10115-sprite",
        filename = ConstEnum.icons .. "/10115.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10201-sprite",
        filename = ConstEnum.icons .. "/10201.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10202-sprite",
        filename = ConstEnum.icons .. "/10202.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10203-sprite",
        filename = ConstEnum.icons .. "/10203.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10204-sprite",
        filename = ConstEnum.icons .. "/10204.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10205-sprite",
        filename = ConstEnum.icons .. "/10205.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10206-sprite",
        filename = ConstEnum.icons .. "/10206.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10207-sprite",
        filename = ConstEnum.icons .. "/10207.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10208-sprite",
        filename = ConstEnum.icons .. "/10208.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10209-sprite",
        filename = ConstEnum.icons .. "/10209.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10210-sprite",
        filename = ConstEnum.icons .. "/10210.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10211-sprite",
        filename = ConstEnum.icons .. "/10211.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10212-sprite",
        filename = ConstEnum.icons .. "/10212.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10213-sprite",
        filename = ConstEnum.icons .. "/10213.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10214-sprite",
        filename = ConstEnum.icons .. "/10214.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10215-sprite",
        filename = ConstEnum.icons .. "/10215.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10301-sprite",
        filename = ConstEnum.icons .. "/10301.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10302-sprite",
        filename = ConstEnum.icons .. "/10302.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10303-sprite",
        filename = ConstEnum.icons .. "/10303.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10304-sprite",
        filename = ConstEnum.icons .. "/10304.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10305-sprite",
        filename = ConstEnum.icons .. "/10305.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10306-sprite",
        filename = ConstEnum.icons .. "/10306.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10307-sprite",
        filename = ConstEnum.icons .. "/10307.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10308-sprite",
        filename = ConstEnum.icons .. "/10308.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10309-sprite",
        filename = ConstEnum.icons .. "/10309.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10310-sprite",
        filename = ConstEnum.icons .. "/10310.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10311-sprite",
        filename = ConstEnum.icons .. "/10311.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10312-sprite",
        filename = ConstEnum.icons .. "/10312.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10313-sprite",
        filename = ConstEnum.icons .. "/10313.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10314-sprite",
        filename = ConstEnum.icons .. "/10314.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10315-sprite",
        filename = ConstEnum.icons .. "/10315.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10401-sprite",
        filename = ConstEnum.icons .. "/10401.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10402-sprite",
        filename = ConstEnum.icons .. "/10402.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10403-sprite",
        filename = ConstEnum.icons .. "/10403.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10404-sprite",
        filename = ConstEnum.icons .. "/10404.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10405-sprite",
        filename = ConstEnum.icons .. "/10405.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10406-sprite",
        filename = ConstEnum.icons .. "/10406.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10407-sprite",
        filename = ConstEnum.icons .. "/10407.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10408-sprite",
        filename = ConstEnum.icons .. "/10408.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10409-sprite",
        filename = ConstEnum.icons .. "/10409.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10410-sprite",
        filename = ConstEnum.icons .. "/10410.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10411-sprite",
        filename = ConstEnum.icons .. "/10411.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10412-sprite",
        filename = ConstEnum.icons .. "/10412.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10413-sprite",
        filename = ConstEnum.icons .. "/10413.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10414-sprite",
        filename = ConstEnum.icons .. "/10414.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10415-sprite",
        filename = ConstEnum.icons .. "/10415.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10501-sprite",
        filename = ConstEnum.icons .. "/10501.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10502-sprite",
        filename = ConstEnum.icons .. "/10502.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10503-sprite",
        filename = ConstEnum.icons .. "/10503.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10504-sprite",
        filename = ConstEnum.icons .. "/10504.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10505-sprite",
        filename = ConstEnum.icons .. "/10505.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10506-sprite",
        filename = ConstEnum.icons .. "/10506.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10507-sprite",
        filename = ConstEnum.icons .. "/10507.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10508-sprite",
        filename = ConstEnum.icons .. "/10508.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10509-sprite",
        filename = ConstEnum.icons .. "/10509.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10510-sprite",
        filename = ConstEnum.icons .. "/10510.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10511-sprite",
        filename = ConstEnum.icons .. "/10511.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10512-sprite",
        filename = ConstEnum.icons .. "/10512.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10513-sprite",
        filename = ConstEnum.icons .. "/10513.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10514-sprite",
        filename = ConstEnum.icons .. "/10514.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "10515-sprite",
        filename = ConstEnum.icons .. "/10515.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2001-sprite",
        filename = ConstEnum.icons .. "/2001.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2002-sprite",
        filename = ConstEnum.icons .. "/2002.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2003-sprite",
        filename = ConstEnum.icons .. "/2003.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200336-sprite",
        filename = ConstEnum.icons .. "/200336.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200337-sprite",
        filename = ConstEnum.icons .. "/200337.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200338-sprite",
        filename = ConstEnum.icons .. "/200338.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200339-sprite",
        filename = ConstEnum.icons .. "/200339.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200340-sprite",
        filename = ConstEnum.icons .. "/200340.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200341-sprite",
        filename = ConstEnum.icons .. "/200341.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200346-sprite",
        filename = ConstEnum.icons .. "/200346.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200347-sprite",
        filename = ConstEnum.icons .. "/200347.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200349-sprite",
        filename = ConstEnum.icons .. "/200349.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200350-sprite",
        filename = ConstEnum.icons .. "/200350.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "200351-sprite",
        filename = ConstEnum.icons .. "/200351.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200352-sprite",
        filename = ConstEnum.icons .. "/200352.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200353-sprite",
        filename = ConstEnum.icons .. "/200353.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200354-sprite",
        filename = ConstEnum.icons .. "/200354.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200367-sprite",
        filename = ConstEnum.icons .. "/200367.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200368-sprite",
        filename = ConstEnum.icons .. "/200368.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200371-sprite",
        filename = ConstEnum.icons .. "/200371.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200372-sprite",
        filename = ConstEnum.icons .. "/200372.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200374-sprite",
        filename = ConstEnum.icons .. "/200374.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200375-sprite",
        filename = ConstEnum.icons .. "/200375.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200376-sprite",
        filename = ConstEnum.icons .. "/200376.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200377-sprite",
        filename = ConstEnum.icons .. "/200377.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200378-sprite",
        filename = ConstEnum.icons .. "/200378.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200379-sprite",
        filename = ConstEnum.icons .. "/200379.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200380-sprite",
        filename = ConstEnum.icons .. "/200380.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200381-sprite",
        filename = ConstEnum.icons .. "/200381.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200382-sprite",
        filename = ConstEnum.icons .. "/200382.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200383-sprite",
        filename = ConstEnum.icons .. "/200383.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200384-sprite",
        filename = ConstEnum.icons .. "/200384.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200385-sprite",
        filename = ConstEnum.icons .. "/200385.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200386-sprite",
        filename = ConstEnum.icons .. "/200386.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200387-sprite",
        filename = ConstEnum.icons .. "/200387.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200388-sprite",
        filename = ConstEnum.icons .. "/200388.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200389-sprite",
        filename = ConstEnum.icons .. "/200389.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200390-sprite",
        filename = ConstEnum.icons .. "/200390.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "200395-sprite",
        filename = ConstEnum.icons .. "/200395.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2004-sprite",
        filename = ConstEnum.icons .. "/2004.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2005-sprite",
        filename = ConstEnum.icons .. "/2005.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2006-sprite",
        filename = ConstEnum.icons .. "/2006.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2007-sprite",
        filename = ConstEnum.icons .. "/2007.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2008-sprite",
        filename = ConstEnum.icons .. "/2008.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2009-sprite",
        filename = ConstEnum.icons .. "/2009.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2010-sprite",
        filename = ConstEnum.icons .. "/2010.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2101-sprite",
        filename = ConstEnum.icons .. "/2101.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2102-sprite",
        filename = ConstEnum.icons .. "/2102.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2103-sprite",
        filename = ConstEnum.icons .. "/2103.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2104-sprite",
        filename = ConstEnum.icons .. "/2104.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2105-sprite",
        filename = ConstEnum.icons .. "/2105.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2106-sprite",
        filename = ConstEnum.icons .. "/2106.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2107-sprite",
        filename = ConstEnum.icons .. "/2107.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2108-sprite",
        filename = ConstEnum.icons .. "/2108.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2109-sprite",
        filename = ConstEnum.icons .. "/2109.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "2110-sprite",
        filename = ConstEnum.icons .. "/2110.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260001-sprite",
        filename = ConstEnum.icons .. "/260001.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260003-sprite",
        filename = ConstEnum.icons .. "/260003.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260007-sprite",
        filename = ConstEnum.icons .. "/260007.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260011-sprite",
        filename = ConstEnum.icons .. "/260011.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260012-sprite",
        filename = ConstEnum.icons .. "/260012.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260019-sprite",
        filename = ConstEnum.icons .. "/260019.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260021-sprite",
        filename = ConstEnum.icons .. "/260021.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260025-sprite",
        filename = ConstEnum.icons .. "/260025.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260029-sprite",
        filename = ConstEnum.icons .. "/260029.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260030-sprite",
        filename = ConstEnum.icons .. "/260030.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260037-sprite",
        filename = ConstEnum.icons .. "/260037.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260039-sprite",
        filename = ConstEnum.icons .. "/260039.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260043-sprite",
        filename = ConstEnum.icons .. "/260043.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260047-sprite",
        filename = ConstEnum.icons .. "/260047.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260048-sprite",
        filename = ConstEnum.icons .. "/260048.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260055-sprite",
        filename = ConstEnum.icons .. "/260055.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260057-sprite",
        filename = ConstEnum.icons .. "/260057.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260061-sprite",
        filename = ConstEnum.icons .. "/260061.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260065-sprite",
        filename = ConstEnum.icons .. "/260065.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260066-sprite",
        filename = ConstEnum.icons .. "/260066.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260073-sprite",
        filename = ConstEnum.icons .. "/260073.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260075-sprite",
        filename = ConstEnum.icons .. "/260075.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260079-sprite",
        filename = ConstEnum.icons .. "/260079.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260083-sprite",
        filename = ConstEnum.icons .. "/260083.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260084-sprite",
        filename = ConstEnum.icons .. "/260084.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260091-sprite",
        filename = ConstEnum.icons .. "/260091.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260093-sprite",
        filename = ConstEnum.icons .. "/260093.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260097-sprite",
        filename = ConstEnum.icons .. "/260097.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260101-sprite",
        filename = ConstEnum.icons .. "/260101.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260102-sprite",
        filename = ConstEnum.icons .. "/260102.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260109-sprite",
        filename = ConstEnum.icons .. "/260109.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260112-sprite",
        filename = ConstEnum.icons .. "/260112.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260116-sprite",
        filename = ConstEnum.icons .. "/260116.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260117-sprite",
        filename = ConstEnum.icons .. "/260117.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260124-sprite",
        filename = ConstEnum.icons .. "/260124.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260127-sprite",
        filename = ConstEnum.icons .. "/260127.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260131-sprite",
        filename = ConstEnum.icons .. "/260131.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260132-sprite",
        filename = ConstEnum.icons .. "/260132.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260139-sprite",
        filename = ConstEnum.icons .. "/260139.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260142-sprite",
        filename = ConstEnum.icons .. "/260142.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260146-sprite",
        filename = ConstEnum.icons .. "/260146.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260147-sprite",
        filename = ConstEnum.icons .. "/260147.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260154-sprite",
        filename = ConstEnum.icons .. "/260154.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260157-sprite",
        filename = ConstEnum.icons .. "/260157.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260161-sprite",
        filename = ConstEnum.icons .. "/260161.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260162-sprite",
        filename = ConstEnum.icons .. "/260162.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260169-sprite",
        filename = ConstEnum.icons .. "/260169.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260172-sprite",
        filename = ConstEnum.icons .. "/260172.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "260173-sprite",
        filename = ConstEnum.icons .. "/260173.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "261001-sprite",
        filename = ConstEnum.icons .. "/261001.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "261002-sprite",
        filename = ConstEnum.icons .. "/261002.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "290001-sprite",
        filename = ConstEnum.icons .. "/290001.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "290011-sprite",
        filename = ConstEnum.icons .. "/290011.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "290021-sprite",
        filename = ConstEnum.icons .. "/290021.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293020-sprite",
        filename = ConstEnum.icons .. "/293020.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293021-sprite",
        filename = ConstEnum.icons .. "/293021.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293022-sprite",
        filename = ConstEnum.icons .. "/293022.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293023-sprite",
        filename = ConstEnum.icons .. "/293023.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293024-sprite",
        filename = ConstEnum.icons .. "/293024.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293025-sprite",
        filename = ConstEnum.icons .. "/293025.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293026-sprite",
        filename = ConstEnum.icons .. "/293026.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293029-sprite",
        filename = ConstEnum.icons .. "/293029.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293030-sprite",
        filename = ConstEnum.icons .. "/293030.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "293031-sprite",
        filename = ConstEnum.icons .. "/293031.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294001-sprite",
        filename = ConstEnum.icons .. "/294001.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294002-sprite",
        filename = ConstEnum.icons .. "/294002.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294003-sprite",
        filename = ConstEnum.icons .. "/294003.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294004-sprite",
        filename = ConstEnum.icons .. "/294004.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294005-sprite",
        filename = ConstEnum.icons .. "/294005.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294006-sprite",
        filename = ConstEnum.icons .. "/294006.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294007-sprite",
        filename = ConstEnum.icons .. "/294007.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294008-sprite",
        filename = ConstEnum.icons .. "/294008.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "294009-sprite",
        filename = ConstEnum.icons .. "/294009.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295001-sprite",
        filename = ConstEnum.icons .. "/295001.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295002-sprite",
        filename = ConstEnum.icons .. "/295002.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295003-sprite",
        filename = ConstEnum.icons .. "/295003.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295004-sprite",
        filename = ConstEnum.icons .. "/295004.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295005-sprite",
        filename = ConstEnum.icons .. "/295005.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295006-sprite",
        filename = ConstEnum.icons .. "/295006.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295013-sprite",
        filename = ConstEnum.icons .. "/295013.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295014-sprite",
        filename = ConstEnum.icons .. "/295014.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295015-sprite",
        filename = ConstEnum.icons .. "/295015.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295025-sprite",
        filename = ConstEnum.icons .. "/295025.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295026-sprite",
        filename = ConstEnum.icons .. "/295026.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295027-sprite",
        filename = ConstEnum.icons .. "/295027.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295028-sprite",
        filename = ConstEnum.icons .. "/295028.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295029-sprite",
        filename = ConstEnum.icons .. "/295029.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295030-sprite",
        filename = ConstEnum.icons .. "/295030.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "295031-sprite",
        filename = ConstEnum.icons .. "/295031.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "296074-sprite",
        filename = ConstEnum.icons .. "/296074.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296075-sprite",
        filename = ConstEnum.icons .. "/296075.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296076-sprite",
        filename = ConstEnum.icons .. "/296076.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296448-sprite",
        filename = ConstEnum.icons .. "/296448.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296449-sprite",
        filename = ConstEnum.icons .. "/296449.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296450-sprite",
        filename = ConstEnum.icons .. "/296450.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296451-sprite",
        filename = ConstEnum.icons .. "/296451.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296452-sprite",
        filename = ConstEnum.icons .. "/296452.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296453-sprite",
        filename = ConstEnum.icons .. "/296453.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296454-sprite",
        filename = ConstEnum.icons .. "/296454.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296455-sprite",
        filename = ConstEnum.icons .. "/296455.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296456-sprite",
        filename = ConstEnum.icons .. "/296456.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296457-sprite",
        filename = ConstEnum.icons .. "/296457.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296458-sprite",
        filename = ConstEnum.icons .. "/296458.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296459-sprite",
        filename = ConstEnum.icons .. "/296459.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296462-sprite",
        filename = ConstEnum.icons .. "/296462.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296463-sprite",
        filename = ConstEnum.icons .. "/296463.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296464-sprite",
        filename = ConstEnum.icons .. "/296464.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296525-sprite",
        filename = ConstEnum.icons .. "/296525.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296526-sprite",
        filename = ConstEnum.icons .. "/296526.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "296527-sprite",
        filename = ConstEnum.icons .. "/296527.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296546-sprite",
        filename = ConstEnum.icons .. "/296546.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296596-sprite",
        filename = ConstEnum.icons .. "/296596.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296597-sprite",
        filename = ConstEnum.icons .. "/296597.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296598-sprite",
        filename = ConstEnum.icons .. "/296598.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296599-sprite",
        filename = ConstEnum.icons .. "/296599.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296600-sprite",
        filename = ConstEnum.icons .. "/296600.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296601-sprite",
        filename = ConstEnum.icons .. "/296601.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296602-sprite",
        filename = ConstEnum.icons .. "/296602.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296642-sprite",
        filename = ConstEnum.icons .. "/296642.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296653-sprite",
        filename = ConstEnum.icons .. "/296653.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296654-sprite",
        filename = ConstEnum.icons .. "/296654.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296655-sprite",
        filename = ConstEnum.icons .. "/296655.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296658-sprite",
        filename = ConstEnum.icons .. "/296658.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296659-sprite",
        filename = ConstEnum.icons .. "/296659.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296660-sprite",
        filename = ConstEnum.icons .. "/296660.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296661-sprite",
        filename = ConstEnum.icons .. "/296661.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296662-sprite",
        filename = ConstEnum.icons .. "/296662.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "296663-sprite",
        filename = ConstEnum.icons .. "/296663.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296664-sprite",
        filename = ConstEnum.icons .. "/296664.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296665-sprite",
        filename = ConstEnum.icons .. "/296665.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296666-sprite",
        filename = ConstEnum.icons .. "/296666.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296701-sprite",
        filename = ConstEnum.icons .. "/296701.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "296704-sprite",
        filename = ConstEnum.icons .. "/296704.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297891-sprite",
        filename = ConstEnum.icons .. "/297891.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297892-sprite",
        filename = ConstEnum.icons .. "/297892.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297893-sprite",
        filename = ConstEnum.icons .. "/297893.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297948-sprite",
        filename = ConstEnum.icons .. "/297948.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297949-sprite",
        filename = ConstEnum.icons .. "/297949.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297950-sprite",
        filename = ConstEnum.icons .. "/297950.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "297951-sprite",
        filename = ConstEnum.icons .. "/297951.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "297952-sprite",
        filename = ConstEnum.icons .. "/297952.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "297953-sprite",
        filename = ConstEnum.icons .. "/297953.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "297964-sprite",
        filename = ConstEnum.icons .. "/297964.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297965-sprite",
        filename = ConstEnum.icons .. "/297965.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297966-sprite",
        filename = ConstEnum.icons .. "/297966.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297967-sprite",
        filename = ConstEnum.icons .. "/297967.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297973-sprite",
        filename = ConstEnum.icons .. "/297973.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297974-sprite",
        filename = ConstEnum.icons .. "/297974.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297975-sprite",
        filename = ConstEnum.icons .. "/297975.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297991-sprite",
        filename = ConstEnum.icons .. "/297991.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297992-sprite",
        filename = ConstEnum.icons .. "/297992.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297993-sprite",
        filename = ConstEnum.icons .. "/297993.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297994-sprite",
        filename = ConstEnum.icons .. "/297994.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297995-sprite",
        filename = ConstEnum.icons .. "/297995.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297996-sprite",
        filename = ConstEnum.icons .. "/297996.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297997-sprite",
        filename = ConstEnum.icons .. "/297997.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "297998-sprite",
        filename = ConstEnum.icons .. "/297998.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298002-sprite",
        filename = ConstEnum.icons .. "/298002.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298003-sprite",
        filename = ConstEnum.icons .. "/298003.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298004-sprite",
        filename = ConstEnum.icons .. "/298004.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298029-sprite",
        filename = ConstEnum.icons .. "/298029.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298030-sprite",
        filename = ConstEnum.icons .. "/298030.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298031-sprite",
        filename = ConstEnum.icons .. "/298031.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298032-sprite",
        filename = ConstEnum.icons .. "/298032.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298033-sprite",
        filename = ConstEnum.icons .. "/298033.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298034-sprite",
        filename = ConstEnum.icons .. "/298034.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298035-sprite",
        filename = ConstEnum.icons .. "/298035.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298036-sprite",
        filename = ConstEnum.icons .. "/298036.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298037-sprite",
        filename = ConstEnum.icons .. "/298037.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298038-sprite",
        filename = ConstEnum.icons .. "/298038.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298201-sprite",
        filename = ConstEnum.icons .. "/298201.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298220-sprite",
        filename = ConstEnum.icons .. "/298220.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298221-sprite",
        filename = ConstEnum.icons .. "/298221.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298222-sprite",
        filename = ConstEnum.icons .. "/298222.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298223-sprite",
        filename = ConstEnum.icons .. "/298223.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298263-sprite",
        filename = ConstEnum.icons .. "/298263.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298264-sprite",
        filename = ConstEnum.icons .. "/298264.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298265-sprite",
        filename = ConstEnum.icons .. "/298265.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298266-sprite",
        filename = ConstEnum.icons .. "/298266.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298267-sprite",
        filename = ConstEnum.icons .. "/298267.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298268-sprite",
        filename = ConstEnum.icons .. "/298268.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298269-sprite",
        filename = ConstEnum.icons .. "/298269.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298279-sprite",
        filename = ConstEnum.icons .. "/298279.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298289-sprite",
        filename = ConstEnum.icons .. "/298289.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298299-sprite",
        filename = ConstEnum.icons .. "/298299.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298309-sprite",
        filename = ConstEnum.icons .. "/298309.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298319-sprite",
        filename = ConstEnum.icons .. "/298319.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298329-sprite",
        filename = ConstEnum.icons .. "/298329.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298339-sprite",
        filename = ConstEnum.icons .. "/298339.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298349-sprite",
        filename = ConstEnum.icons .. "/298349.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298359-sprite",
        filename = ConstEnum.icons .. "/298359.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298369-sprite",
        filename = ConstEnum.icons .. "/298369.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298379-sprite",
        filename = ConstEnum.icons .. "/298379.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298389-sprite",
        filename = ConstEnum.icons .. "/298389.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298396-sprite",
        filename = ConstEnum.icons .. "/298396.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298403-sprite",
        filename = ConstEnum.icons .. "/298403.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298410-sprite",
        filename = ConstEnum.icons .. "/298410.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298417-sprite",
        filename = ConstEnum.icons .. "/298417.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298424-sprite",
        filename = ConstEnum.icons .. "/298424.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298431-sprite",
        filename = ConstEnum.icons .. "/298431.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298432-sprite",
        filename = ConstEnum.icons .. "/298432.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298501-sprite",
        filename = ConstEnum.icons .. "/298501.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298502-sprite",
        filename = ConstEnum.icons .. "/298502.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298503-sprite",
        filename = ConstEnum.icons .. "/298503.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298504-sprite",
        filename = ConstEnum.icons .. "/298504.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298505-sprite",
        filename = ConstEnum.icons .. "/298505.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298506-sprite",
        filename = ConstEnum.icons .. "/298506.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298507-sprite",
        filename = ConstEnum.icons .. "/298507.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298508-sprite",
        filename = ConstEnum.icons .. "/298508.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298509-sprite",
        filename = ConstEnum.icons .. "/298509.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298510-sprite",
        filename = ConstEnum.icons .. "/298510.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298511-sprite",
        filename = ConstEnum.icons .. "/298511.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298512-sprite",
        filename = ConstEnum.icons .. "/298512.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298513-sprite",
        filename = ConstEnum.icons .. "/298513.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298921-sprite",
        filename = ConstEnum.icons .. "/298921.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298922-sprite",
        filename = ConstEnum.icons .. "/298922.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298923-sprite",
        filename = ConstEnum.icons .. "/298923.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298924-sprite",
        filename = ConstEnum.icons .. "/298924.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298925-sprite",
        filename = ConstEnum.icons .. "/298925.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298928-sprite",
        filename = ConstEnum.icons .. "/298928.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298929-sprite",
        filename = ConstEnum.icons .. "/298929.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298930-sprite",
        filename = ConstEnum.icons .. "/298930.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298931-sprite",
        filename = ConstEnum.icons .. "/298931.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298932-sprite",
        filename = ConstEnum.icons .. "/298932.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298933-sprite",
        filename = ConstEnum.icons .. "/298933.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298934-sprite",
        filename = ConstEnum.icons .. "/298934.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298935-sprite",
        filename = ConstEnum.icons .. "/298935.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298936-sprite",
        filename = ConstEnum.icons .. "/298936.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298937-sprite",
        filename = ConstEnum.icons .. "/298937.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298938-sprite",
        filename = ConstEnum.icons .. "/298938.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298942-sprite",
        filename = ConstEnum.icons .. "/298942.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298943-sprite",
        filename = ConstEnum.icons .. "/298943.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298944-sprite",
        filename = ConstEnum.icons .. "/298944.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298945-sprite",
        filename = ConstEnum.icons .. "/298945.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298946-sprite",
        filename = ConstEnum.icons .. "/298946.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298947-sprite",
        filename = ConstEnum.icons .. "/298947.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298948-sprite",
        filename = ConstEnum.icons .. "/298948.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298949-sprite",
        filename = ConstEnum.icons .. "/298949.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298950-sprite",
        filename = ConstEnum.icons .. "/298950.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298951-sprite",
        filename = ConstEnum.icons .. "/298951.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298952-sprite",
        filename = ConstEnum.icons .. "/298952.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298953-sprite",
        filename = ConstEnum.icons .. "/298953.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298954-sprite",
        filename = ConstEnum.icons .. "/298954.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298955-sprite",
        filename = ConstEnum.icons .. "/298955.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298956-sprite",
        filename = ConstEnum.icons .. "/298956.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298957-sprite",
        filename = ConstEnum.icons .. "/298957.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298958-sprite",
        filename = ConstEnum.icons .. "/298958.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298959-sprite",
        filename = ConstEnum.icons .. "/298959.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298960-sprite",
        filename = ConstEnum.icons .. "/298960.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298961-sprite",
        filename = ConstEnum.icons .. "/298961.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298962-sprite",
        filename = ConstEnum.icons .. "/298962.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298963-sprite",
        filename = ConstEnum.icons .. "/298963.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298964-sprite",
        filename = ConstEnum.icons .. "/298964.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298965-sprite",
        filename = ConstEnum.icons .. "/298965.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298966-sprite",
        filename = ConstEnum.icons .. "/298966.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298967-sprite",
        filename = ConstEnum.icons .. "/298967.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298968-sprite",
        filename = ConstEnum.icons .. "/298968.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298969-sprite",
        filename = ConstEnum.icons .. "/298969.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298970-sprite",
        filename = ConstEnum.icons .. "/298970.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298971-sprite",
        filename = ConstEnum.icons .. "/298971.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298972-sprite",
        filename = ConstEnum.icons .. "/298972.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298973-sprite",
        filename = ConstEnum.icons .. "/298973.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "298974-sprite",
        filename = ConstEnum.icons .. "/298974.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298975-sprite",
        filename = ConstEnum.icons .. "/298975.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298976-sprite",
        filename = ConstEnum.icons .. "/298976.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298977-sprite",
        filename = ConstEnum.icons .. "/298977.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "298978-sprite",
        filename = ConstEnum.icons .. "/298978.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299051-sprite",
        filename = ConstEnum.icons .. "/299051.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299052-sprite",
        filename = ConstEnum.icons .. "/299052.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299053-sprite",
        filename = ConstEnum.icons .. "/299053.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299054-sprite",
        filename = ConstEnum.icons .. "/299054.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299055-sprite",
        filename = ConstEnum.icons .. "/299055.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299056-sprite",
        filename = ConstEnum.icons .. "/299056.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299057-sprite",
        filename = ConstEnum.icons .. "/299057.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299058-sprite",
        filename = ConstEnum.icons .. "/299058.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299059-sprite",
        filename = ConstEnum.icons .. "/299059.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299060-sprite",
        filename = ConstEnum.icons .. "/299060.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299061-sprite",
        filename = ConstEnum.icons .. "/299061.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299062-sprite",
        filename = ConstEnum.icons .. "/299062.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299063-sprite",
        filename = ConstEnum.icons .. "/299063.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299064-sprite",
        filename = ConstEnum.icons .. "/299064.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299065-sprite",
        filename = ConstEnum.icons .. "/299065.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299066-sprite",
        filename = ConstEnum.icons .. "/299066.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299067-sprite",
        filename = ConstEnum.icons .. "/299067.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "299068-sprite",
        filename = ConstEnum.icons .. "/299068.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "c_chenghao_01-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_01.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_02-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_02.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_03-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_03.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_04-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_04.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_05-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_05.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_06-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_06.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_07-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_07.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_08-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_08.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_09-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_09.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_10-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_10.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_11-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_11.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_12-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_12.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_13-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_13.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_14-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_14.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_15-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_15.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_16-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_16.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_17-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_17.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_18-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_18.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_19-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_19.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_20-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_20.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_21-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_21.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_22-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_22.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_23-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_23.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_24-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_24.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_25-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_25.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_26-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_26.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_27-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_27.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_28-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_28.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_29-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_29.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_30-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_30.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_31-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_31.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_32-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_32.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_33-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_33.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_34-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_34.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_35-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_35.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_36-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_36.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_37-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_37.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_38-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_38.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_39-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_39.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_40-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_40.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_41-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_41.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_42-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_42.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_43-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_43.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_44-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_44.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_45-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_45.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_46-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_46.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_47-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_47.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_48-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_48.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_49-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_49.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_50-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_50.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_51-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_51.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_52-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_52.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_53-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_53.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_54-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_54.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_55-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_55.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_56-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_56.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_57-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_57.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_58-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_58.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_59-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_59.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_60-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_60.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_61-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_61.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_62-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_62.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_63-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_63.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_64-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_64.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_65-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_65.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_66-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_66.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_67-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_67.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_68-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_68.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_69-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_69.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_70-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_70.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chenghao_71-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_71.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_72-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_72.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_73-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_73.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_74-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_74.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_75-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_75.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_76-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_76.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_77-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_77.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_78-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_78.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_79-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_79.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_80-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_80.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_81-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_81.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chenghao_82-sprite",
        filename = ConstEnum.icons .. "/c_chenghao_82.png",
        size = 512,
    },
    {
        type = "sprite",
        name = "c_chibang_06-sprite",
        filename = ConstEnum.icons .. "/c_chibang_06.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_07-sprite",
        filename = ConstEnum.icons .. "/c_chibang_07.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_08-sprite",
        filename = ConstEnum.icons .. "/c_chibang_08.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_09-sprite",
        filename = ConstEnum.icons .. "/c_chibang_09.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_10-sprite",
        filename = ConstEnum.icons .. "/c_chibang_10.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_11-sprite",
        filename = ConstEnum.icons .. "/c_chibang_11.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_12-sprite",
        filename = ConstEnum.icons .. "/c_chibang_12.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_13-sprite",
        filename = ConstEnum.icons .. "/c_chibang_13.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_14-sprite",
        filename = ConstEnum.icons .. "/c_chibang_14.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "c_chibang_15-sprite",
        filename = ConstEnum.icons .. "/c_chibang_15.png",
        size = 256,
    },
    {
        type = "sprite",
        name = "j_xwch_1-sprite",
        filename = ConstEnum.icons .. "/j_xwch_1.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_10-sprite",
        filename = ConstEnum.icons .. "/j_xwch_10.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_11-sprite",
        filename = ConstEnum.icons .. "/j_xwch_11.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_12-sprite",
        filename = ConstEnum.icons .. "/j_xwch_12.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_13-sprite",
        filename = ConstEnum.icons .. "/j_xwch_13.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_14-sprite",
        filename = ConstEnum.icons .. "/j_xwch_14.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_15-sprite",
        filename = ConstEnum.icons .. "/j_xwch_15.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_16-sprite",
        filename = ConstEnum.icons .. "/j_xwch_16.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_17-sprite",
        filename = ConstEnum.icons .. "/j_xwch_17.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_18-sprite",
        filename = ConstEnum.icons .. "/j_xwch_18.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_19-sprite",
        filename = ConstEnum.icons .. "/j_xwch_19.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_2-sprite",
        filename = ConstEnum.icons .. "/j_xwch_2.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_20-sprite",
        filename = ConstEnum.icons .. "/j_xwch_20.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_21-sprite",
        filename = ConstEnum.icons .. "/j_xwch_21.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_22-sprite",
        filename = ConstEnum.icons .. "/j_xwch_22.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_23-sprite",
        filename = ConstEnum.icons .. "/j_xwch_23.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_24-sprite",
        filename = ConstEnum.icons .. "/j_xwch_24.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_25-sprite",
        filename = ConstEnum.icons .. "/j_xwch_25.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_26-sprite",
        filename = ConstEnum.icons .. "/j_xwch_26.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_27-sprite",
        filename = ConstEnum.icons .. "/j_xwch_27.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_28-sprite",
        filename = ConstEnum.icons .. "/j_xwch_28.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_29-sprite",
        filename = ConstEnum.icons .. "/j_xwch_29.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_3-sprite",
        filename = ConstEnum.icons .. "/j_xwch_3.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_30-sprite",
        filename = ConstEnum.icons .. "/j_xwch_30.png",
        size = 128,
    },
    {
        type = "sprite",
        name = "j_xwch_4-sprite",
        filename = ConstEnum.icons .. "/j_xwch_4.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_5-sprite",
        filename = ConstEnum.icons .. "/j_xwch_5.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_6-sprite",
        filename = ConstEnum.icons .. "/j_xwch_6.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_7-sprite",
        filename = ConstEnum.icons .. "/j_xwch_7.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_8-sprite",
        filename = ConstEnum.icons .. "/j_xwch_8.png",
        size = 64,
    },
    {
        type = "sprite",
        name = "j_xwch_9-sprite",
        filename = ConstEnum.icons .. "/j_xwch_9.png",
        size = 64,
    },
})
